---
name: aliased
version: 0.30
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Use shorter versions of class names.
license: perl
resources:
  license: ~
requires:
  Test::More: 0
provides:
  aliased:
    file: lib/aliased.pm
    version: 0.30
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
