---
abstract: 'Use shorter versions of class names.'
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: aliased
provides:
  aliased:
    file: lib/aliased.pm
    version: '0.32'
resources:
  license: http://dev.perl.org/licenses/
version: '0.32'
